version: '2'
services:
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=a436a28ef460af588091b37bde45685efcdcf7be97cb6d19aab190e8ae370308 --http.api "db,personal,eth,net,web3" --http.corsdomain="*" --networkid=20211234 --http --http.addr="0.0.0.0"'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth:
    build: monitored-geth-client
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --http.corsdomain="*" --networkid=20211234 --http --bootnodes="enode://7056aeb5f9eea6d2636de0e0ca5205dab3f70ee9ce8397349ac8aedd2e8e5700f72c73b71dfd565ba5a95b145395821e5a1a52ddf2f9c1e2ccf87be9f347f27a@XXX:30303"'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
